### ISSUE TITLE
Mouse unreliable

### ISSUE THREAD

**Issue by Zardoz89** [adam4813/Sigma#39] opened 2013-10-19 13:45 UTC
The mouse moves a bit the view, sometimes moves better, but is nearly inusable. Putting a simple printf inside of GLFPSController::MouseMove (GLFPSController.cpp), fix its. 
Could be that Sigma is trying to apply the rotation forces too many times or too fast and this make it unreliable ? This will explain why a dumb printf fix it.

**Comment by wrongu** [comment] 2013-10-19 17:49
I had a thought about this but im without computer for the weekend.

We should limit the tick rate of the whole engine, not just the graphics. Currently the graphics system limits rendering to 60fps, but updates can happen faster. Its hard to make my mouse move more than a few pixels per tick since they are so frequent, and i think that may be causing the weird mouse behavior.
PLUS if we standardize the tick rate of the whole engine, we might avoid similar speed-dependent bugs in the future.

**Comment by Zardoz89** [comment] 2013-10-19 18:11
The dampening value and/or the delta value should depend of the tick rate.
I know games that using SDL1.2 can run over 100 fps and not does weird
things with the mice (Unreal Tournament, Zandronum, etc...)

2013/10/19 wrongu notifications@github.com

> I had a thought about this but im without computer for the weekend.
> 
> We should limit the tick rate of the whole engine, not just the graphics.
> Currently the graphics system limits rendering to 60fps, but updates can
> happen faster. Its hard to make my mouse move more than a few pixels per
> tick since they are so frequent, and i think that may be causing the weird
> mouse behavior.
> PLUS if we standardize the tick rate of the whole engine, we might avoid
> similar speed-dependent bugs in the future.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/adam4813/Sigma/issues/39#issuecomment-26655085
> .

## 

I'm afraid that I have a blog: http://zardoz.es

**Comment by kmclarnon** [comment] 2013-10-19 18:13
You absolutely should fix your time step.  Not doing so will just cause you all sorts of headaches and doesn't gain you anything.

**Comment by tanderegg** [comment] 2013-10-19 20:42
Right now all movement should be proportional to the amound of time that passed within that frame.  This is generally preferable to hard limiting the frame rate itself, since it allows faster computers to run the app more smoothly.  The problem with the mouse is that we are resetting it's movement every frame to avoid a "drift" caused by the force-based rotation method we are using.  I'm working on removing that problem.  Otherwise object movement and rotation should be constant regardless of machine speed.

**Comment by kmclarnon** [comment] 2013-10-19 21:02
Fixing your time step means fixing the chunk of time the simulation consumes, it doesn't mean that you have to fix your frame rate

**Comment by Zardoz89** [comment] 2013-10-19 21:15
Bullet not allow to set rotation angles directly, instead of using forces ? I did with bepu physics.

**Comment by adam4813** [comment] 2013-10-19 22:04
No the rotation isn't done in bullet yet.

**Comment by wrongu** [comment] 2013-10-19 22:12
@tanderegg, I'm not convinced that different machines having different time steps for physics is a good thing. Let the faster machines render more frames per second, but lets try to keep physics consistent for everyone. Its less "limiting" and more "standardizing"

**Comment by tanderegg** [comment] 2013-10-19 23:31
The physics is already set to units of time, so for example a rotation force of 1.0f around Y means 1.0f units per second regardless of how many times per second the simulation executes.  Currently the renderer is set to only render at 60fps, but all other logic processings happens as fast as the machine can execute it.  If we set the physics system to execute once per render, it wouldn't really gain us anything that I can see.  We may want to limit the amount of time that the physics system can execute per frame at some point to free up processing time for other things, but that's not yet a problem.

**Comment by kmclarnon** [comment] 2013-10-20 02:33
If you're using bullet for physics already, then internally it is already using a fixed time step integration that just repeats until it has caught up with the elapsed frame time.  You can advance the simulation once per update loop and it should be fine.

**Comment by adam4813** [comment] 2013-10-20 03:02
Once again rotation is not handled by bullet physics.

**Comment by wrongu** [comment] 2013-10-20 17:39
I think this has gone tangentially to two topics.
1) what is wrong with the mouse and how can it be fixed?
2) which subsystems, if any, should be restricted to a maximum update frequency? (Graphics, physics, I/O, etc.)

#2 deserves more thorough discussion. Can somebody make a forum topic for it?

**Comment by adam4813** [comment] 2013-10-20 18:41
There is a pr in the queue for the mouse issue.

**Comment by adam4813** [comment] 2013-10-23 00:45
Ok the PR has been merged. I am going to close this, if it is still unreliable reopen this.

**Closed as completed by adam4813** 2013-10-23 00:45 UTC
